metricbeat.config.modules.path: "/etc/metricbeat/modules.d/*.yml"
metricbeat.config.modules:
  - module: system
    metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - uptime
    - socket_summary
    - core
    - diskio
    reload.enabled: true
    period: 5s
    processes: ['.*']
    cpu.metrics: ["percentages"]
    core.metrics: ["percentages"]
  # Period on which files under path should be checked for changes
  #reload.period: 10s

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false


output.logstash:
  hosts: ["10.0.0.11:9004"]

#processors:
#- add_fields:
#    target: robot
#    fields:
#      id: '${HOSTNAME:unknown}'

logging.level: error
